spring.application.name=chatop
spring.datasource.url=jdbc:mysql://localhost:3306/chatop
spring.datasource.username=elvis
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
